export const CONFIG = {
	invalidCharactersError: 'Please remove invalid characters to continue.',
	departureRequiredError: 'Please enter your departure city.',
	departureCityMinLengthError: 'Departure city must be atleast <x> characters long.',
	departureCityMaxLengthError: 'Departure city cannot be greater than <x> characters long.',
	arrivalRequiredError: 'Please enter your destination city.',
	arrivalCityMinLengthError: 'Destination city must be atleast 3 characters long.',
	arrivalCityMaxLengthError: 'Destination city cannot be greater than <x> characters long.',
	departureDateRequiredError: 'Please enter your departure date.',
	departureDatePatternError: 'Please enter your departure date in <x> format only.',
	departureDateInPastError: 'Departure date cannot be in the past.',
	returnDateRequiredError: 'Please enter your return date.',
	returnDatePatternError: 'Please enter your return date in <x> format only.',
	returnDateInPastError: 'Return date cannot be in the past.',
	returnDateBeforeThanDepartureDateError: 'Return date cannot be before the departure date.',
	numberOfPassengersRequiredError: 'Please enter number of passengers travelling.',
	numberOfPassengersGreaterThanFiveError: 'Maximum 5 passengers can be booked in one booking',
	numberOfPassengersMinimumError: 'Minimum 1 passenger must be travelling.',
	travelClassRequiredError: 'Please select the class of your travel.',
	dateFormat: 'dd/mm/yyyy',
	departureCityMinLength: 3,
	departureCityMaxLength: 50,
	arrivalCityMinLength: 3,
	arrivalCityMaxLength: 50
}